#pragma once

/**** FX data header generated by fxdata-build.py tool version 1.15 ****/

using uint24_t = __uint24;

// Initialize FX hardware using  FX::begin(FX_DATA_PAGE); in the setup() function.

constexpr uint16_t FX_DATA_PAGE  = 0xffb5;
constexpr uint24_t FX_DATA_BYTES = 18968;

constexpr uint24_t title_gfx = 0x000000;
constexpr uint16_t title_gfx_width  = 128;
constexpr uint16_t title_gfx_height = 64;

constexpr uint24_t tiles = 0x000404;
constexpr uint16_t tilesWidth  = 8;
constexpr uint16_t tilesHeight = 8;
constexpr uint8_t  tilesFrames = 131;

constexpr uint24_t portals = 0x000820;
constexpr uint16_t portalsWidth  = 16;
constexpr uint16_t portalsHeight = 16;
constexpr uint8_t  portalsFrames = 20;

constexpr uint24_t player_gfx = 0x000AA4;
constexpr uint16_t player_gfx_width  = 16;
constexpr uint16_t player_gfx_height = 16;
constexpr uint8_t  player_gfx_frames = 8;

constexpr uint24_t guardians_h_gfx = 0x000BA8;
constexpr uint16_t guardians_h_gfx_width  = 16;
constexpr uint16_t guardians_h_gfx_height = 16;
constexpr uint8_t  guardians_h_gfx_frames = 136;

constexpr uint24_t guardians_v_gfx = 0x001CAC;
constexpr uint16_t guardians_v_gfx_width  = 16;
constexpr uint16_t guardians_v_gfx_height = 16;
constexpr uint8_t  guardians_v_gfx_frames = 43;

constexpr uint24_t tilemap = 0x002210;
constexpr uint24_t Level_1 = 0x002218;
constexpr uint24_t Level_2 = 0x002418;
constexpr uint24_t Level_3 = 0x002618;
constexpr uint24_t Level_4 = 0x002818;
constexpr uint24_t Level_5 = 0x002A18;
constexpr uint24_t Level_6 = 0x002C18;
constexpr uint24_t Level_7 = 0x002E18;
constexpr uint24_t Level_8 = 0x003018;
constexpr uint24_t Level_9 = 0x003218;
constexpr uint24_t Level_10 = 0x003418;
constexpr uint24_t Level_11 = 0x003618;
constexpr uint24_t Level_12 = 0x003818;
constexpr uint24_t Level_13 = 0x003A18;
constexpr uint24_t Level_14 = 0x003C18;
constexpr uint24_t Level_15 = 0x003E18;
constexpr uint24_t Level_16 = 0x004018;
constexpr uint24_t Level_17 = 0x004218;
constexpr uint24_t Level_18 = 0x004418;
constexpr uint24_t Level_19 = 0x004618;
constexpr uint24_t Level_20 = 0x004818;
